#!/usr/bin/env python3
"""
Pre-render the site: one real HTML file per page per language.

Why this exists
---------------
Everything used to be assembled in the browser. A crawler asking for
/study.html got an empty <div> and a script tag, so the 9,639 word entries and
280 grammar patterns - the most searchable thing on the site - were invisible
to it. And all twelve languages shared one URL, because the picker only wrote
to localStorage, so there was nothing for hreflang to point at.

This writes the translated text and the study tables straight into the markup,
and gives every language its own address:

    /                     English (also x-default)
    /ne/, /ja/, /vi/ ...  the other eleven
    /study/n5-words.html  one page per level per list, content in the HTML

The pages still load the same scripts afterwards, so behaviour is unchanged
for a browser; the difference is only what arrives before JavaScript runs.

Run:  python3 tools/build_static.py
"""

import io
import json
import os
import re
import shutil
from urllib.parse import quote
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://jlpt.sureshsurkheti.com"
DEFAULT_LANG = "en"

# Page -> whether search engines should index it.
CORE_PAGES = {
    "index.html": True,
    "levels.html": True,
    # Merged into levels.html; the file survives only to forward old links,
    # so it must stay out of the index and out of the sitemap.
    "practice.html": False,
    "exams.html": True,
    "study.html": True,
    "about.html": True,
    "stats.html": False,
    "exam.html": False,
    # A viewer for one character, built in the browser from ?k=. The content
    # a crawler should have is the level list it opens from, which is already
    # indexed; 2,211 near-identical shells would only compete with it.
    "kanji.html": False,
}

LEVELS = ["n5", "n4", "n3", "n2", "n1"]
KINDS = ["words", "kanji", "grammar"]
COUNT_KEY = {"words": "study.wordsCount", "kanji": "study.kanjiCount",
             "grammar": "study.patternsCount"}
# The noun the page calls itself. Grammar is the exception: the tab beside
# Vocabulary and Kanji stays "Grammar" because that is navigation, but the
# heading and the <title> say "Core Grammar" - 59 patterns presented as "N1
# Grammar" claims to be the level's grammar, and it is about a third of it.
NOUN_KEY = {"words": "study.words", "kanji": "study.kanji",
            "grammar": "study.grammarCore"}


# --------------------------------------------------------------------------
# translations
# --------------------------------------------------------------------------

def load_translations():
    src = io.open(os.path.join(ROOT, "assets/js/i18n-strings.js"),
                  encoding="utf-8").read()
    out = {}
    for lang, body in re.findall(r'I18N\.register\("([\w-]+)",\s*(\{.*?\n\}\);)',
                                 src, re.S):
        body = re.sub(r",(\s*\})", r"\1", body.rstrip(");").rstrip())
        out[lang] = json.loads(body)
    return out


def write_language_files(tr):
    """One small script per language instead of one big one for all twelve.

    assets/js/i18n-strings.js holds every language in a single file - 219 KB
    raw, 52 KB gzipped - and every page loaded all of it. Eleven twelfths of
    that was a language the visitor was not reading, and it was the largest
    asset on the site by a wide margin, larger than either stylesheet.

    Nothing needs it all any more: the language picker navigates to that
    language's own URL rather than repainting the page in place, so a page is
    only ever rendered in the one language it was built for. Each page now
    loads English (the fallback for any key a translation is missing) plus
    its own language, and nothing else.

    The big file stays where it is as the single source to edit; it is simply
    no longer served to anybody.
    """
    outdir = os.path.join(ROOT, "assets", "i18n")
    os.makedirs(outdir, exist_ok=True)
    for lang, table in tr.items():
        body = json.dumps(table, ensure_ascii=False, indent=1, sort_keys=True)
        io.open(os.path.join(outdir, lang + ".js"), "w", encoding="utf-8").write(
            "/* Generated by tools/build_static.py from "
            "assets/js/i18n-strings.js - do not edit. */\n"
            'I18N.register("%s", %s);\n' % (lang, body))
    return len(tr)


def t(table, key, fallback_table):
    if key in table:
        return table[key]
    return fallback_table.get(key, key)


def esc(text):
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


# --------------------------------------------------------------------------
# rendering one page
# --------------------------------------------------------------------------

def apply_i18n(html, table, en):
    """Fill every data-i18n hook the way the browser script would."""

    def text_sub(m):
        tag, attrs, key = m.group(1), m.group(2), m.group(3)
        return "<%s%s>%s</%s>" % (tag, attrs, esc(t(table, key, en)), tag)

    html = re.sub(
        r'<(\w+)([^>]*\sdata-i18n="([^"]+)"[^>]*)>.*?</\1>',
        text_sub, html, flags=re.S)

    def html_sub(m):
        tag, attrs, key = m.group(1), m.group(2), m.group(3)
        return "<%s%s>%s</%s>" % (tag, attrs, t(table, key, en), tag)

    html = re.sub(
        r'<(\w+)([^>]*\sdata-i18n-html="([^"]+)"[^>]*)>.*?</\1>',
        html_sub, html, flags=re.S)

    def attr_sub(m):
        spec = m.group(1)
        parts = []
        for pair in spec.split(","):
            bits = pair.split(":")
            if len(bits) == 2:
                parts.append('%s="%s"' % (bits[0].strip(),
                                          esc(t(table, bits[1].strip(), en))))
        return 'data-i18n-attr="%s" %s' % (spec, " ".join(parts))

    return re.sub(r'data-i18n-attr="([^"]+)"', attr_sub, html)


def absolutise(html):
    """Root-relative asset paths, so /ne/index.html loads the same files."""
    for attr in ("href", "src"):
        html = re.sub(r'(%s=")(assets/|favicon|apple-touch|icon-|site\.web)'
                      % attr, r"\1/\2", html)
    # internal page links keep working from inside a language directory
    html = re.sub(r'href="((?:index|levels|practice|exams|study|about|stats|exam)\.html[^"]*)"',
                  r'href="./\1"', html)
    return html


def page_url(lang, page):
    prefix = "" if lang == DEFAULT_LANG else "/" + lang
    if page == "index.html":
        return SITE + prefix + "/"
    return SITE + prefix + "/" + page


def study_url(lang, level, kind):
    prefix = "" if lang == DEFAULT_LANG else "/" + lang
    return "%s%s/study/%s-%s.html" % (SITE, prefix, level, kind)


# English titles are hand-tuned for the phrases people actually search. Every
# other language derives its title and description from strings the site is
# already translated with, so there is nothing extra to keep in sync.
EN_META = {
    "index.html": ("JLPT Practice — Free Mock Exams for N1, N2, N3, N4 and N5",
                   "home.body"),
    "exams.html": ("JLPT Mock Exam Library — 84 Full-Length Practice Papers",
                   "exams.body"),
    "study.html": ("JLPT Kanji, Vocabulary and Grammar Lists — N5 to N1",
                   "study.body"),
    "levels.html": ("JLPT Levels Explained — N1, N2, N3, N4 and N5 Requirements",
                    "levels.body"),
    "practice.html": ("JLPT Practice by Section — Vocabulary, Grammar, Reading, "
                      "Listening", "practice.body"),
    "about.html": ("About JLPT Practice — Free and Private JLPT Study",
                   "about.body"),
    "stats.html": ("Your JLPT Progress — JLPT Practice", "stats.body"),
    "exam.html": ("JLPT Mock Exam — JLPT Practice", "exam.setupNote"),
    "kanji.html": ("Kanji Stroke Order and Readings — JLPT Practice",
                   "study.body"),
}

TITLE_KEY = {
    "index.html": "home.title", "exams.html": "exams.title",
    "study.html": "study.title", "levels.html": "levels.title",
    "practice.html": "practice.title", "about.html": "about.title",
    "stats.html": "stats.title", "exam.html": "tag.exam",
    "kanji.html": "study.kanji",
}

SITE_NAME = "JLPT Practice"
AUTHOR_NAME = "Suresh Surkheti"

# Where takedown and rights requests go. Published on the about page, so it
# must be an address the owner is willing to make public - change it here and
# rebuild; it is not written into any template by hand.
CONTACT_EMAIL = "surkhetisuresh123@gmail.com"

COUNTS = {}


def meta_for(lang, page, table, en):
    body_key = EN_META[page][1]
    desc = t(table, body_key, en)
    if lang == DEFAULT_LANG:
        return EN_META[page][0], desc
    title = t(table, TITLE_KEY[page], en)
    if page != "index.html":
        title = "%s — %s" % (title, SITE_NAME)
    return title, desc


def json_ld(lang, url, title, desc, url_of):
    """One WebSite node and one WebPage node, linked."""
    root = SITE + ("/" if lang == DEFAULT_LANG else "/" + lang + "/")

    site = {
        "@type": "WebSite",
        "@id": root + "#website",
        "url": root,
        "name": SITE_NAME,
        "inLanguage": lang,
        "description": desc,
        "publisher": {"@type": "Person", "name": AUTHOR_NAME},
    }
    page = {
        "@type": "WebPage",
        "@id": url + "#webpage",
        "url": url,
        "name": title,
        "description": desc,
        "inLanguage": lang,
        "isPartOf": {"@id": root + "#website"},
    }

    graph = [site, page]
    return ('    <script type="application/ld+json">%s</script>'
            % json.dumps({"@context": "https://schema.org", "@graph": graph},
                         ensure_ascii=False, separators=(",", ":")))


def hreflang_block(langs, url_of):
    rows = ['    <link rel="alternate" hreflang="%s" href="%s" />' % (l, url_of(l))
            for l in langs]
    rows.append('    <link rel="alternate" hreflang="x-default" href="%s" />'
                % url_of(DEFAULT_LANG))
    return "\n".join(rows)


def seo_head(lang, url, title, desc, langs, url_of, indexable, extra=""):
    out = ["    <title>%s</title>" % esc(title),
           '    <meta name="description" content="%s" />' % esc(desc)]
    if indexable:
        out.append('    <link rel="canonical" href="%s" />' % url)
        out.append('    <meta name="robots" content="index, follow, '
                   'max-image-preview:large" />')
        out.append(hreflang_block(langs, url_of))
    else:
        out.append('    <meta name="robots" content="noindex, follow" />')
    out += [
        '    <meta property="og:type" content="website" />',
        '    <meta property="og:site_name" content="%s" />' % SITE_NAME,
        '    <meta property="og:locale" content="%s" />' % lang.replace("-", "_"),
        '    <meta property="og:title" content="%s" />' % esc(title),
        '    <meta property="og:description" content="%s" />' % esc(desc),
        '    <meta property="og:url" content="%s" />' % url,
        '    <meta property="og:image" content="%s/og-card.jpg" />' % SITE,
        # Stated dimensions let a platform reserve the right box before it has
        # fetched the file, which is the difference between a large card and a
        # small one on a first paste.
        '    <meta property="og:image:width" content="1200" />',
        '    <meta property="og:image:height" content="630" />',
        '    <meta property="og:image:alt" content="%s" />' % esc(SITE_NAME),
        '    <meta name="twitter:card" content="summary_large_image" />',
        '    <meta name="twitter:title" content="%s" />' % esc(title),
        '    <meta name="twitter:description" content="%s" />' % esc(desc),
        '    <meta name="twitter:image" content="%s/og-card.jpg" />' % SITE,
    ]
    # Structured data. There was none: a search engine had to infer what the
    # site is from the prose. These three nodes say it outright - what the
    # site is, who publishes it, and where this page sits in it - which is
    # what earns a sitelinks block and a breadcrumb trail in a result rather
    # than a bare blue link.
    out.append(json_ld(lang, url, title, desc, url_of))
    if extra:
        out.append(extra)
    return "\n".join(out) + "\n"


def rewrite_head(html, lang, page, langs, indexable, table, en, extra=""):
    html = re.sub(r'<html lang="[^"]*"', '<html lang="%s"' % lang, html, count=1)
    title, desc = meta_for(lang, page, table, en)
    head = seo_head(lang, page_url(lang, page), title, desc, langs,
                    lambda l: page_url(l, page), indexable, extra)
    # replace everything the previous generator left between <title> and the fonts
    start = html.index("<title>")
    end = html.index('<link rel="preconnect"')
    return html[:start] + head.lstrip() + "    " + html[end:]


def language_links(langs, page, current, names, table, en):
    """A crawlable set of links to the other languages.

    The picker in the header is a <select>, which no crawler can follow, so
    each translation needs a real <a> somewhere on the page or the twelve
    language trees are invisible to everything but the sitemap. This row is
    that link. It goes inside the footer's own .container - written loose
    after </footer> it inherited no width and no list styling, and landed as
    a bulleted list against the left edge of every page."""
    items = []
    for lang in langs:
        if lang == current:
            continue
        items.append('<li><a href="%s" hreflang="%s" lang="%s">%s</a></li>'
                     % (page_url(lang, page), lang, lang, esc(names[lang])))
    label = esc(t(table, "lang.label", en))
    return ('      <nav class="container lang-links" aria-label="%s">\n'
            '        <span>%s</span>\n'
            '        <ul>%s</ul>\n'
            '      </nav>\n    ' % (label, label, "".join(items)))


# --------------------------------------------------------------------------
# study tables, written into the markup
# --------------------------------------------------------------------------

LEVEL_COLOR_CLASS = {"n1": "level-n1", "n2": "level-n2", "n3": "level-n3",
                     "n4": "level-n4", "n5": "level-n5"}


def site_counts():
    """The figures the home page advertises, counted from the data files at
    build time. Typed into a template they would quietly go stale the first
    time a list grew; counted here they cannot."""
    counts = {"words": 0, "kanji": 0, "grammar": 0, "nepali": 0, "papers": 0}
    for level in LEVELS:
        for kind, field in (("words", "words"), ("kanji", "kanji"),
                            ("grammar", "patterns")):
            path = os.path.join(ROOT, "data", kind, level + ".json")
            if not os.path.exists(path):
                continue
            items = json.load(io.open(path, encoding="utf-8"))[field]
            counts[kind] += len(items)
            # Nepali is counted across words and grammar together, because
            # that is what somebody asking "is it in Nepali?" wants to know.
            if kind != "kanji":
                counts["nepali"] += sum(1 for x in items if x.get("ne"))
    idx = os.path.join(ROOT, "data", "exams", "index.json")
    if os.path.exists(idx):
        counts["papers"] = len(json.load(io.open(idx, encoding="utf-8"))["exams"])
    return counts


def coverage_counts():
    """How many words and patterns each level holds, and how many of them
    carry a Nepali gloss. Read from the data files at build time so the panel
    cannot drift from what the lists actually contain."""
    out = {}
    for level in LEVELS:
        row = {}
        for kind, field in (("words", "words"), ("kanji", "kanji"),
                            ("grammar", "patterns")):
            path = os.path.join(ROOT, "data", kind, level + ".json")
            if not os.path.exists(path):
                row[kind] = (0, 0)
                continue
            items = json.load(io.open(path, encoding="utf-8"))[field]
            row[kind] = (len(items), sum(1 for x in items if x.get("ne")))
        out[level] = row
    return out


def coverage_panel(table, en, here=None, prefix="study/"):
    """A five-row summary of what the lists hold and which languages the
    meanings are written in.

    It answers the two questions somebody arrives with - "is my level here?"
    and "is it in my language?" - without clicking through five tabs, and it
    is the only thing that links the ten list pages to each other. `here` is
    the "<level>-<kind>" page being written, so the panel does not link a
    page to itself."""
    counts = coverage_counts()
    head = "".join(
        '<th scope="col"%s>%s</th>' % (attr, label) for attr, label in (
            (' data-i18n="notice.colLevel"', esc(t(table, "notice.colLevel", en))),
            (' data-i18n="study.words"', esc(t(table, "study.words", en))),
            (' data-i18n="study.kanji"', esc(t(table, "study.kanji", en))),
            (' data-i18n="study.grammar"', esc(t(table, "study.grammar", en))),
            ("", "English"),
            (' lang="ne"', "\u0928\u0947\u092a\u093e\u0932\u0940"),
        ))

    rows = []
    for level in ["n5", "n4", "n3", "n2", "n1"]:
        c = counts[level]
        cells = []
        for kind in ("words", "kanji", "grammar"):
            total = c[kind][0]
            if not total:
                cells.append('<td><span class="coverage-no">&mdash;</span></td>')
                continue
            text = "{:,}".format(total)
            page = "%s-%s" % (level, kind)
            cells.append('<td>%s</td>' % (
                '<span class="is-here">%s</span>' % text if page == here
                else '<a href="%s%s.html">%s</a>' % (prefix, page, text)))

        # English is on every entry; Nepali is complete for N5 and N4 and
        # covers the grammar patterns at every level. Say which, rather than
        # printing a tick that overstates it.
        ne_words, ne_gram = c["words"][1], c["grammar"][1]
        if ne_words and ne_gram:
            ne = '<span class="coverage-yes">&#10003;</span>'
        elif ne_gram:
            ne = ('<span class="coverage-yes">&#10003;</span> '
                  '<span class="coverage-part">%s</span>'
                  % esc(t(table, "study.grammar", en)))
        else:
            ne = '<span class="coverage-no">&mdash;</span>'

        rows.append(
            '<tr><th scope="row"><span class="lv-chip %s">%s</span></th>'
            '%s<td><span class="coverage-yes">&#10003;</span></td><td>%s</td></tr>'
            % (LEVEL_COLOR_CLASS[level], level.upper(), "".join(cells), ne))

    return ('<section class="study-coverage">\n'
            '        <h2 data-i18n="notice.title">%s</h2>\n'
            '        <div class="coverage-wrap">\n'
            '          <table class="coverage-table">\n'
            '            <thead><tr>%s</tr></thead>\n'
            '            <tbody>%s</tbody>\n'
            '          </table>\n'
            '        </div>\n'
            '      </section>'
            % (esc(t(table, "notice.title", en)), head, "".join(rows)))


FIELD = {"words": "words", "kanji": "kanji", "grammar": "patterns"}


def study_rows(level, kind, table, en, up=""):
    """`up` is the hop back to the language root: the hub page at
    /study.html links to kanji.html beside it, the level pages at
    /study/n5-kanji.html need ../kanji.html."""
    path = os.path.join(ROOT, "data", kind, level + ".json")
    if not os.path.exists(path):
        return "", 0
    data = json.load(io.open(path, encoding="utf-8"))
    rows = data[FIELD[kind]]

    out = []
    if kind == "words":
        out.append('<div class="study-row is-head"><span>%s</span>'
                   '<span>%s</span><span>%s</span></div>'
                   % (esc(t(table, "study.colWord", en)),
                      esc(t(table, "study.colReading", en)),
                      esc(t(table, "study.colMeaning", en))))
        for r in rows:
            ne = ('<em class="study-ne">%s</em>' % esc(r["ne"])) \
                if (table is not en and r.get("ne")) else ""
            affix = ('<b class="study-affix">%s</b>'
                     % esc(t(table, "study.affix", en))) if r.get("affix") else ""
            out.append(
                '<div class="study-row">'
                '<span class="study-jp">%s%s</span>'
                '<span class="study-reading">%s%s</span>'
                '<span class="study-en">%s%s</span></div>'
                % (esc(r["w"]), affix, esc(r.get("r", "")),
                   ('<em>%s</em>' % esc(r["romaji"])) if r.get("romaji") else "",
                   esc(r["en"]), ne))
    elif kind == "kanji":
        out.append('<div class="study-row is-head is-kanji"><span>%s</span>'
                   '<span>%s</span><span>%s</span></div>'
                   % (esc(t(table, "study.kanji", en)),
                      esc(t(table, "study.colReading", en)),
                      esc(t(table, "study.colMeaning", en))))
        strokes = esc(t(table, "study.colStrokes", en))
        order = esc(t(table, "study.strokeOrder", en))
        for r in rows:
            # KANJIDIC's own notation is kept: a dot in a kun reading is the
            # boundary between the character and its okurigana, a hyphen marks
            # a prefix or suffix reading. Stripping either would teach the
            # wrong word.
            on = ('<b>\u97f3</b> %s' % "\u30fb".join(esc(x) for x in r["on"])) \
                if r["on"] else ""
            kun = ("<b>\u8a13</b> " + "\u30fb".join(
                (esc(x.split(".", 1)[0]) +
                 '<i class="kanji-okuri">%s</i>' % esc(x.split(".", 1)[1]))
                if "." in x else esc(x) for x in r["kun"])) if r["kun"] else ""

            ex = "".join(
                '<span class="kanji-ex"><b>%s</b> <i>%s</i> %s%s</span>'
                % (esc(e["w"]), esc(e.get("r", "")), esc(e.get("en", "")),
                   ('<em class="study-ne">%s</em>' % esc(e["ne"]))
                   if (table is not en and e.get("ne")) else "")
                for e in r["ex"])

            out.append(
                '<div class="study-row is-kanji" data-kanji="%s">'
                '<span class="kanji-cell">'
                '<a class="kanji-char" href="%skanji.html?k=%s&amp;lv=%s" '
                'aria-expanded="false" title="%s">%s</a>'
                '<span class="kanji-strokes">%d %s</span></span>'
                '<span class="kanji-readings">%s%s%s</span>'
                '<span class="study-en">%s%s</span></div>'
                % (esc(r["k"]), up, quote(r["k"]), level, order, esc(r["k"]),
                   r["s"], strokes,
                   on, "<br />" if on and kun else "", kun,
                   esc(", ".join(r["en"])),
                   ('<span class="kanji-exs">%s</span>' % ex) if ex else ""))
    else:
        out.append('<div class="study-row is-head is-grammar"><span>%s</span>'
                   '<span>%s</span><span>%s</span></div>'
                   % (esc(t(table, "study.colPattern", en)),
                      esc(t(table, "study.colMeaning", en)),
                      esc(t(table, "study.colExample", en))))
        for r in rows:
            ne = ('<em class="study-ne">%s</em>' % esc(r["ne"])) \
                if (table is not en and r.get("ne")) else ""
            out.append(
                '<div class="study-row is-grammar">'
                '<span class="study-jp">%s</span>'
                '<span class="study-en">%s%s</span>'
                '<span class="study-example"><b>%s</b><em>%s</em></span></div>'
                % (esc(r["p"]), esc(r["en"]), ne, esc(r["ja"]), esc(r["ex"])))
    return "\n      ".join(out), len(rows)


def main():
    tr = load_translations()
    write_language_files(tr)
    global COUNTS
    COUNTS = site_counts()
    en = tr[DEFAULT_LANG]
    langs = list(tr.keys())
    names = {"en": "English", "ja": "日本語", "ne": "नेपाली", "vi": "Tiếng Việt",
             "id": "Bahasa Indonesia", "fil": "Filipino", "si": "සිංහල",
             "hi": "हिन्दी", "pt-BR": "Português (Brasil)", "zh": "中文",
             "ko": "한국어", "bn": "বাংলা"}

    written = []
    for lang in langs:
        table = tr[lang]
        outdir = ROOT if lang == DEFAULT_LANG else os.path.join(ROOT, lang)
        if lang != DEFAULT_LANG:
            os.makedirs(outdir, exist_ok=True)

        for page, indexable in CORE_PAGES.items():
            src = io.open(os.path.join(ROOT, "_src", page), encoding="utf-8").read()
            html = apply_i18n(src, table, en)
            html = html.replace("%%CONTACT%%", CONTACT_EMAIL)
            if page == "index.html":
                html = html.replace(
                    "</head>",
                    '    <script>window.SITE_COUNTS=%s;</script>\n  </head>'
                    % json.dumps(COUNTS, separators=(",", ":")))
            html = rewrite_head(html, lang, page, langs, indexable, table, en)
            # The takedown address again, this time for the interface strings.
            #
            # %%CONTACT%% is substituted in the markup above, which is what a
            # crawler and a no-script visitor read - but the About page's
            # rights paragraph carries data-i18n-html, so the client-side
            # translator overwrote that good markup with the raw table entry
            # on every page load. Every visitor with JavaScript on was shown
            # "%%CONTACT%%" and a mailto: link pointing at it, on the one
            # paragraph whose entire job is to let a rights holder reach the
            # site without filing a notice.
            #
            # The address stays defined once, here. i18n.js substitutes the
            # same token at lookup time using this value, so the table and
            # the markup can no longer drift apart.
            html = html.replace(
                "</head>",
                '    <script>window.SITE_CONTACT=%s;</script>\n  </head>'
                % json.dumps(CONTACT_EMAIL))
            # English is always present as the fallback; a translated page
            # adds its own table after it. See write_language_files().
            if lang != DEFAULT_LANG:
                html = html.replace(
                    '<script src="assets/i18n/en.js"></script>',
                    '<script src="assets/i18n/en.js"></script>\n'
                    '    <script src="assets/i18n/%s.js"></script>' % lang)
            if lang != DEFAULT_LANG:
                html = absolutise(html)

            # the study page carries its first list in the markup
            if page == "study.html":
                html = html.replace('<div id="studyCoverage"></div>',
                                    coverage_panel(table, en, None, "study/"))
                body, n = study_rows("n5", "words", table, en)
                html = html.replace(
                    '<div id="studyContent" aria-live="polite"></div>',
                    '<div id="studyContent" aria-live="polite">\n'
                    '      <p class="study-count">%d %s</p>\n'
                    '      <div class="study-list">\n      %s\n      </div>\n'
                    '    </div>' % (n, esc(t(table, "study.wordsCount", en)), body))

            html = html.replace(
                "</footer>",
                language_links(langs, page, lang, names, table, en) + "</footer>")

            io.open(os.path.join(outdir, page), "w", encoding="utf-8").write(html)
            if indexable:
                written.append((page_url(lang, page), lang, page))

    # ---------------------------------------------------------------- study
    # One address per level per list. This is the content most likely to be
    # searched for ("N5 vocabulary list with meanings"), and until now all ten
    # of them shared a single URL that arrived empty.
    tpl = io.open(os.path.join(ROOT, "_src", "study.html"), encoding="utf-8").read()
    study_pages = 0
    for lang in langs:
        table = tr[lang]
        base = ROOT if lang == DEFAULT_LANG else os.path.join(ROOT, lang)
        os.makedirs(os.path.join(base, "study"), exist_ok=True)

        for level in LEVELS:
            for kind in KINDS:
                body, n = study_rows(level, kind, table, en, "../")
                if not n:
                    continue
                lv = level.upper()
                noun = t(table, NOUN_KEY[kind], en)
                title = "%s %s — %s" % (lv, noun, SITE_NAME)
                desc = "%s %s: %d %s. %s" % (
                    lv, noun, n, t(table, COUNT_KEY[kind], en),
                    t(table, "study.body", en))

                url = study_url(lang, level, kind)
                ld = ('    <script type="application/ld+json">'
                      '{"@context":"https://schema.org","@type":"DefinedTermSet",'
                      '"name":%s,"url":%s,"inDefinedTermSet":%s,'
                      '"numberOfItems":%d}</script>'
                      % (json.dumps(title), json.dumps(url),
                         json.dumps(SITE + "/study.html"), n))

                html = apply_i18n(tpl, table, en)
                html = re.sub(r'<html lang="[^"]*"', '<html lang="%s"' % lang,
                              html, count=1)
                head = seo_head(lang, url, title, desc, langs,
                                lambda l, lv=level, k=kind: study_url(l, lv, k),
                                True, ld)
                a, b = html.index("<title>"), html.index('<link rel="preconnect"')
                html = html[:a] + head.lstrip() + "    " + html[b:]

                # The heading must name this page, not the section it lives
                # in: ten pages all headed "Vocabulary and grammar lists"
                # compete with each other for the same phrase. Dropping the
                # data-i18n hook stops the script overwriting it on load.
                html = re.sub(r'<h1 data-i18n="study.title">[^<]*</h1>',
                              "<h1>%s %s</h1>" % (esc(lv), esc(noun)), html)

                # Same panel, but the links are siblings in this directory
                # and this page is not a link to itself. It is what connects
                # the ten list pages: without it each one is a dead end.
                html = html.replace(
                    '<div id="studyCoverage"></div>',
                    coverage_panel(table, en, "%s-%s" % (level, kind), ""))

                html = html.replace(
                    '<div id="studyContent" aria-live="polite"></div>',
                    '<div id="studyContent" aria-live="polite">\n'
                    '      <p class="study-count">%d %s</p>\n'
                    '      <div class="study-list">\n      %s\n      </div>\n'
                    '    </div>' % (n, esc(t(table, COUNT_KEY[kind], en)), body))

                if kind == "grammar":
                    html = html.replace(
                        '<div class="study-list">',
                        '<p class="study-note">%s</p>\n      '
                        '<div class="study-list">'
                        % esc(t(table, "study.grammarNote", en)), 1)
                # mark the level and list this page opens on
                html = html.replace('data-level="N5" role="tab">N5',
                                    'data-level="N5" role="tab" %s>N5'
                                    % ("" if lv != "N5" else ""))
                html = re.sub(r'class="study-tab is-on" data-level="N5"',
                              'class="study-tab" data-level="N5"', html)
                html = re.sub(r'class="study-tab" data-level="%s"' % lv,
                              'class="study-tab is-on" data-level="%s"' % lv, html)
                if kind != "words":
                    html = html.replace('class="study-tab is-on" data-kind="words"',
                                        'class="study-tab" data-kind="words"')
                    html = html.replace(
                        'class="study-tab" data-kind="%s"' % kind,
                        'class="study-tab is-on" data-kind="%s"' % kind)
                html = html.replace("</footer>", language_links(
                    langs, "study/%s-%s.html" % (level, kind), lang, names,
                    table, en) + "</footer>")
                # These sit a directory down, and the page above them is the
                # study hub, not the home page the template names.
                html = html.replace('data-back-to="index.html"',
                                    'data-back-to="../study.html"')
                html = absolutise(html)
                html = html.replace('href="./', 'href="../' if lang == DEFAULT_LANG
                                    else 'href="../')

                io.open(os.path.join(base, "study", "%s-%s.html" % (level, kind)),
                        "w", encoding="utf-8").write(html)
                written.append((url, lang, "study"))
                study_pages += 1

    print("wrote %d core pages and %d study pages across %d languages"
          % (len(CORE_PAGES) * len(langs), study_pages, len(langs)))

    # -------------------------------------------------------------- sitemap
    today = date.today().isoformat()
    rows = []
    for url, lang, page in written:
        pri = "1.0" if page == "index.html" else (
            "0.9" if page in ("study", "exams.html") else "0.7")
        rows.append("  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n"
                    "    <priority>%s</priority>\n  </url>" % (url, today, pri))
    io.open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows) + "\n</urlset>\n")
    print("sitemap.xml: %d urls" % len(rows))

    io.open(os.path.join(ROOT, "robots.txt"), "w", encoding="utf-8").write(
        "User-agent: *\nAllow: /\n\n"
        "# One paper per ?id=, all served from the same shell.\n"
        "Disallow: /exam.html\n"
        "Disallow: /kanji.html\n"
        "Disallow: /stats.html\n"
        "Disallow: /_src/\n\n"
        "# The exam papers themselves. The questions are the copyright of\n"
        "# JEES and the Japan Foundation; this site holds them so a learner\n"
        "# can sit a paper, not so they can be re-indexed and re-published.\n"
        "# Search engines index the library page instead.\n"
        "Disallow: /data/exams/\n"
        "Disallow: /data/glossary/\n"
        "Disallow: /data/exams-manual/\n\n"
        "Sitemap: %s/sitemap.xml\n" % SITE)
    print("robots.txt written")


if __name__ == "__main__":
    main()
